### ISSUE TITLE
Support for parameters with white spaces

### ISSUE THREAD

**Issue by wojciech-kulik** [johnno1962/xcodemake#1]
It looks like the script doesn't support white spaces for parameters wrapped with quotes. For example, I pass `-scheme "Something Something"` and it ends up as `-scheme Something Something` and the script fails.

**Comment by johnno1962** [comment]
How about now? https://github.com/johnno1962/xcodemake/commit/bae12e831a15cd49058f392bcc4e306df9e46fca

**Comment by wojciech-kulik** [comment]
Now it created the Makefile, but I don't know how to use it. Calling `make` prints:
```
make: Nothing to be done for `default'.
```

**Comment by johnno1962** [comment]
Does the Makefile look complete? At the end of the file does it have an entry main: dependent on your executables? If it does you should be able to edit a file and just type "make" (or run xcodemake again) and stuff will happen. Can you email me the Makefile, GitHub at johnholdsworth.com?

**Comment by johnno1962** [comment]
I've pushed another commit to force an xcodebuild with `-config Debug`, without which the compilations cannot be extracted. Let me know if this fixes it if there was a problem. You'll need to remove the xcodebuild.log to force regeneration.

**Comment by wojciech-kulik** [comment]
Now it works 🔥 Thank you!

**Comment by johnno1962** [comment]
Thanks for being an early adopter! Still ironing out the details and the README - would you say it was useful/faster than xcodebuild for your project?

**Comment by wojciech-kulik** [comment]
Yes, it's faster but I'm not yet sure how confidently I could integrate it with my project. How does it handle for example changes in the project? Like adding a new file, changing build settings, etc.? Do I have to call `xcodemake` every time I change something else than code?

**Comment by johnno1962** [comment]
This is a good point. I've added some code to try to recapture the xcodebuild in the event of a make failure for any reason so the script should be self-righting now. You should generally use `xcodemake` as the bulk of the time it will just call `make`. Yes, for anything other than code that doesn't cause an error like settings you have to remove the .log files to force a xcodebuild when you next xcodemake.

**Comment by johnno1962** [comment]
P.S. I amend pushed a further change to recapture the xcodebuild whenever you edit the project file which will cater for new or renamed files and settings changes as well.
